### ISSUE TITLE
Generated draft does not list changes

### ISSUE THREAD

**Issue by vslynko** [toolmantim/release-drafter#70]
I have a PR merged, draft is indeed generated, but it does not list that PR. Actually it says "no changes".
May be related to #29, but it happens to me today.

Unfortunately my repository is private.
May be it's possible to check the logs.
On the image there might be useful info to search the logs for, like PR number, commit etc
Thanks in advance.

![image](https://user-images.githubusercontent.com/12891283/45483436-3721dc00-b751-11e8-8bd5-9999ee2dedab.png)

**Comment by vslynko** [comment]
no I have more PRs merged but draft is not updated at all

**Comment by grillermo** [comment]
Its broken for me too

**Comment by trucalling** [comment]
happening with me as well for a private repo

**Comment by trucalling** [comment]
the organization is `vy-labs` and the repo is `labs-core-reloaded `

**Comment by grillermo** [comment]
mine is aliada-mx and the repo is tandem-api

**Comment by trucalling** [comment]
I have release drafter enabled only for one repo in my organization. The latest draft is from 16 hours ago - Sep 27, 2018, 7:07 PM GMT+5:30.

![image](https://user-images.githubusercontent.com/609574/46190517-7c2d3d00-c311-11e8-8804-c33cbc531da1.png)
![image](https://user-images.githubusercontent.com/609574/46190575-bbf42480-c311-11e8-9047-9b9cd3db4c20.png)

**Comment by grillermo** [comment]
The last release sucessfuly written by release drafter on  aliada-mx/tandem-api was at 2018-09-10T18:05:08Z for version v3.29.44 and commit hash efd7f70, if that helps you find it.
The previous release was done at 2018-09-07T22:35:27Z for the same repo.
After those, it stopped working.

**Comment by chasemccoy** [comment]
@toolmantim I am having this same issue with my org's private repository. Uninstalling and reinstalling the app didn't seem to help. The org is `@sproutsocial` and the repository is `seeds`.

**Comment by chasemccoy** [comment]
In fact, the app generated 2 drafts for me for 2 different PRs, instead of one draft for both PRs. Both drafts were empty.

**Comment by elithrar** [comment]
Also seeing a similar issue on [`gorilla/sessions`](https://github.com/gorilla/sessions/releases) - there are 3 commits since the last release, but the draft release only shows 1.

Is the service missing webhooks/GitHub not delivering them?

**Comment by toolmantim** [comment]
Sorry there's been issues… it seems to be only affecting a small number of installs. I've just pushed some updates which might fix some of these issues. Can people give it another go, and let me know the org/repo again if it's still not working as expected?

**Comment by chasemccoy** [comment]
@toolmantim Still not working for me. The org/repo is `@sproutsocial/seeds`.

**Comment by trucalling** [comment]
still not working for me as well. repo is `vy-labs/labs-core-reloaded`

**Comment by grillermo** [comment]
I know this is an open source project and free of charge, i would like with the debugging of this issue by setting up the app my self, are there any pointers where to start? any help to do this appreciated
I really want to fix this for my repo and i'm willing to put in the hours.
Thanks

**Comment by trucalling** [comment]
willing to help in any way possible as well

**Comment by toolmantim** [comment]
Thanks for the offer @grillermo. I realised I had a logging bug (fixed in #79) which meant I was having trouble tracking this down, but if you could spin up your own local copy to debug it'd be much appreciated.

I've just updated the development instructions in 23e737c — since Probot v7.2.0 it's much easier to run an app locally, thanks to @wilhelmklopp, @bkeepers, and @hiimbex.

**Comment by grillermo** [comment]
I managed to debug it and a copy of the app i made its working (on Heroku), it literally changed nothing of the code but i'm not sure the permissions are the same. 
To the my copy of the github app i gave:
Subscription to Push events
Read and Write to Repository Contents
Read Only to Repository metadata
Read Only to Repository webhooks

**Comment by toolmantim** [comment]
I'm glad you got it working @grillermo — thanks for setting it up. It's disturbing that you changed literally nothing and it was working for you.

The only permissions difference I can see is that I don't have "Repository webhooks" read or write enabled at all. Any reason you enabled that?

**Comment by toolmantim** [comment]
I've just requested updated GitHub application permissions from everyone who has this installed. Let me know if that sorts things out for you.

**Comment by trucalling** [comment]
Sadly it still doesn't work. I tried uninstalling and adding the app again but it is still generating empty drafts. I will try and setup a copy of the app to debug this over the weekend. Will let you know if I can diagnose what is causing this.

**Comment by TimonVS** [comment]
@trucalling you're not by any chance using rebase merging, right? :)

**Comment by trucalling** [comment]
no, i am using squash and merge.

**Comment by prathamghadge** [comment]
@toolmantim I am facing a similar issue. 
Making the repo public made the changes appear. 
They went away as soon as I changed it to a private repo again.
Any help on this?

**Comment by dcastil** [comment]
I have the same issue. In private repositories the release drafter doesn't work. In public repos it works though.

**Comment by zhigang1992** [comment]
I can confirm that this is happening because this app doesn't request permission to Pull Request.

It works on public repo because their PRs are public.

It wills on my fork after adding Pull Request Read Access.

@toolmantim

**Comment by zhigang1992** [comment]
@dcastil if you want to try it out now before it got updated by @toolmantim 
You try https://github.com/apps/release-drafter-private

**Comment by toolmantim** [comment]
Thanks for debugging it @zhigang1992 — I’ve requested updated permissions.

If y’all like to give it another go.

**Comment by dcastil** [comment]
Hey @toolmantim! Sorry for letting you wait so long. I can confirm that it works in private repositories now. 😊 Thanks for the fix!
